btrfs-tools: Add dependency on lzo acl e2fsprogs
Add dependency on lzo acl e2fsprogs to fix the below building failure
1. commit b268a417259b9[add lzo compression support to restore] needs lzo
	cmds-restore.c:30:25: fatal error: lzo/lzoconf.h: No such file or directory

2. btrfs-tools includes <sys/acl.h> which is provided by acl
	btrfs-convert.c:32:21: fatal error: sys/acl.h: No such file or directory

3. btrfs-tools always needs e2fsprogs
	btrfs-convert.c:44:28: fatal error: ext2fs/ext2_fs.h: No such file or directory

Signed-off-by: Roy.Li <rongqing.li@windriver.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>